'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type DdsButtonCustomEvent } from "@dubai-design-system/components-js";
import { DdsAlert as DdsAlertElement, defineCustomElement as defineDdsAlert } from "@dubai-design-system/components-js/dist/components/dds-alert.js";
import { DdsButton as DdsButtonElement, defineCustomElement as defineDdsButton } from "@dubai-design-system/components-js/dist/components/dds-button.js";
import { DdsLink as DdsLinkElement, defineCustomElement as defineDdsLink } from "@dubai-design-system/components-js/dist/components/dds-link.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type DdsAlertEvents = { onCloseEvent: EventName<CustomEvent<void>> };

export const DdsAlert: StencilReactComponent<DdsAlertElement, DdsAlertEvents> = /*@__PURE__*/ createComponent<DdsAlertElement, DdsAlertEvents>({
    tagName: 'dds-alert',
    elementClass: DdsAlertElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onCloseEvent: 'closeEvent' } as DdsAlertEvents,
    defineCustomElement: defineDdsAlert
});

type DdsButtonEvents = { onDdsClick: EventName<DdsButtonCustomEvent<MouseEvent>> };

export const DdsButton: StencilReactComponent<DdsButtonElement, DdsButtonEvents> = /*@__PURE__*/ createComponent<DdsButtonElement, DdsButtonEvents>({
    tagName: 'dds-button',
    elementClass: DdsButtonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onDdsClick: 'ddsClick' } as DdsButtonEvents,
    defineCustomElement: defineDdsButton
});

type DdsLinkEvents = NonNullable<unknown>;

export const DdsLink: StencilReactComponent<DdsLinkElement, DdsLinkEvents> = /*@__PURE__*/ createComponent<DdsLinkElement, DdsLinkEvents>({
    tagName: 'dds-link',
    elementClass: DdsLinkElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdsLinkEvents,
    defineCustomElement: defineDdsLink
});
